# Font
font-family = JetBrains Mono
font-size = 13
font-thicken = true
adjust-cell-height = 2

# Theme
theme = Catppuccin Mocha
background-opacity = 0.85
background-blur-radius = 30

# Window
window-padding-x = 16
window-padding-y = 10
window-padding-balance = true
window-padding-color = extend
window-decoration = true
confirm-close-surface = false
gtk-titlebar = true

# Cursor
cursor-style = block
cursor-style-blink = false
cursor-color = #f5e0dc

# Mouse
mouse-hide-while-typing = true

# Clipboard
copy-on-select = clipboard
clipboard-paste-protection = false

# Bold is bright
bold-is-bright = true

# Shell integration
shell-integration = detect

# Shell
command = /usr/bin/zsh

# Neovim/tmux compatibility
window-inherit-working-directory = true
